// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQh1TreZVrvXlRQYKD1Pk5T0ilgeYIGg',
    appId: '1:299294924284:web:d754bf77631a8b19afe679',
    messagingSenderId: '299294924284',
    projectId: 'find-a-tutor-80a53',
    authDomain: 'find-a-tutor-80a53.firebaseapp.com',
    storageBucket: 'find-a-tutor-80a53.firebasestorage.app',
    measurementId: 'G-NRVL3PTNM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKks4FIe7_8agXog5n5L7401Oiq5UTOM',
    appId: '1:299294924284:android:248f060f349a2cb8afe679',
    messagingSenderId: '299294924284',
    projectId: 'find-a-tutor-80a53',
    storageBucket: 'find-a-tutor-80a53.firebasestorage.app',
  );
}
